### PR TITLE
codespell: use stdin

### PR DESCRIPTION
**Pull request by Jendker**

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
I'm sorry but this is way too complex and it wouldn't work on PUC Lua 5.1 because it has no goto

Does codespell support output format options? Or is it possible to use a different errorformat pattern instead?

**Comment by Jendker** [comment]
Hi @mfussenegger, thank you for looking into this!

I have created a PR to codespell which will make parsing easier. https://github.com/codespell-project/codespell/pull/3224
Let's see how it goes from there.

**Comment by Jendker** [comment]
@mfussenegger there is a discussion going in my codespell PR: https://github.com/codespell-project/codespell/pull/3224 Please feel free to add any comments there.

**Comment by Jendker** [comment]
The codespell changes have been merged an I will be able to vastly simplify this PR. I'll wait for the release of codespell and then push new version of the code.

**Comment by mfussenegger** [comment]
Closing this for now. Please open a new PR once the codespell release is out and you've adapted it to that.

**Pull request closed without merging**
