### PR TITLE
Ensure stdout/stderr pipes get closed

### PR DESCRIPTION
**Pull request by mfussenegger**
Should fix https://github.com/mfussenegger/nvim-lint/issues/215

### CODE REVIEW

**Comment by mfussenegger** [comment]
@nifoc Could you try if this still works with `deadnix` ? The change in https://github.com/mfussenegger/nvim-lint/pull/209 unfortunately causes file descriptors to leak

**Comment by nifoc** [comment]
This seems to break `deadnix` again, but I suppose leaking file descriptors is worse than one linter (that isn't even part of the default configuration) breaking.

**Comment by mfussenegger** [comment]
> This seems to break `deadnix` again, but I suppose leaking file descriptors is worse than one linter (that isn't even part of the default configuration) breaking.

Thank you for checking. I pushed another commit that still fixes the leak and might keep `deadnix` working. Could you give it another try?

**Comment by nifoc** [comment]
Just tested with [f510830](https://github.com/mfussenegger/nvim-lint/pull/218/commits/f51083092875dad4da718313e0385db22596126d) and `deadnix` still works as expected 🥳

**Pull request merged**
