### PR TITLE
Add htmlhint (simple html linter)

### PR DESCRIPTION
**Pull request by dante0624**

### CODE REVIEW

**Comment by mfussenegger** [comment]
Could you fix the linter errors and add it also to the readme?

**Comment by dante0624** [comment]
Done, hopefully its goode now

**Comment by mfussenegger** [comment]
Thanks

**Comment by m-tranter** [comment]
I am trying to use htmlhint (I used Lazy to get my config setup). It's not bringing in the diaganistics. At the moment I have just added this in lint.lua:
`lint.linters_by_ft = {
    html = { 'htmlhint' },
  }`
Can anyone help with the correct config?

**Pull request merged**
