### PR TITLE
feat(commitlint): add commitlint linter

### PR DESCRIPTION
**Pull request by msyavuz**
TODO
- [x] Add tests
- [x] Updae the README

### CODE REVIEW

**Comment by pbnj** [comment]
Hi @msyavuz, might need to add a test and update the README to include the tool.

**Comment by msyavuz** [comment]
> Hi @msyavuz, might need to add a test and update the README to include the tool.

I will try and do that, thank you.

**Comment by mfussenegger** [comment]
@msyavuz Could you resolve the conflict? I can't amend to the PR because you created it from the master branch. (Please don't do that in the future. Always create a feature branch for PRs)

**Comment by msyavuz** [comment]
@mfussenegger Sorry for that

**Pull request merged**
