### PR TITLE
Eslint d fix error without line number

### PR DESCRIPTION
**Pull request by kasdeya**
This is a quick fix for eslint_d returning diagnostics without line numbers.  #416 
sorry for the formatting changes, this fixes the error I was having, I think the error was that sometimes eslint_d will return errors without line number, this will print that error in the first line of the file as a warning like it used to happen on previous versions, let me know what you think.

### CODE REVIEW

**Comment by sQVe** [comment]
I think it would be better if we properly validated the  diagnostics rather than doing on off checks like this. Since the `eslint` output isn't reliable, I wouldn't be surprised if it could return `nil` for more values than `line`.

**Comment by kasdeya** [comment]
@sQVe  from what I saw eslint_d will always return a message, a severity and a code if there is a diagnostic, only the line number could be nil, since if there's no diagnostic message then there's no diagnostic from what I understand.

**Comment by kasdeya** [comment]
I think an if else statement might work better though, just in case there's both, messages without line numbers and with line numbers in the same diagnostic.

**Comment by sQVe** [comment]
@kasdeya I just pushed https://github.com/mfussenegger/nvim-lint/pull/423, could you give it a glance?

I think it's more robust and lenient, with a bunch of new tests to verify.

**Comment by kasdeya** [comment]
closing this now in favor of #423

**Pull request closed without merging**
