### PR TITLE
Use `stderr` for `stylelint`

### LINKED ISSUE #500: stylelint doesn't lint
CleanShot 2024-01-02 at 13 29 53

I don't get any diagnostics for existing error

Seems like `stdout.read_start` callback is called once https://github.com/mfussenegger/nvim-lint/blob/4dbc7ec60b33b656f7c54bb945671a55b18699f2/lua/lint.lua#L147

and here https://github.com/mfussenegger/nvim-lint/blob/4dbc7ec60b33b656f7c54bb945671a55b18699f2/lua/lint.lua#L77 both args `err, chunk` are `nil`

My config https://github.com/kapral18/config.nvim/blob/dee5f388194a315bfbf7d8587b7d3ce8de9dbe60/lua/plugins/css.lua#L42 (lazyvim based)

Nvim: nvim 0.10.0

### PR DESCRIPTION
**Pull request by jmpolom**
This seems to and should resolve #500

### CODE REVIEW

**Comment by mfussenegger** [comment]
@cpof-tea can you double check this? You made the last changes to this linter, and I don't use it.

**Comment by jmpolom** [comment]
Looks like at some point stylelint changed from outputting problems to `stdout` to `stderr`: https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-16.md#breaking-changes

**Comment by cpof-tea** [comment]
@jmpolom indeed. I have stylelint v14.15.0, and it outputs to `stdout`

@mfussenegger is there any way we can dynamically change `stream` property for backward compatibility?

**Comment by mfussenegger** [comment]
If the linter doesn't output anything in the other stream, setting `both` could be an option.

Otherwise the linter could be implemented as `function()` that first calls `stylelint --version` (if that's supported), parses the version and depending on that returns a different table. But not sure if that's worth it.

**Comment by jmpolom** [comment]
`stylelint -v` does return a version string. Would it be possible to define the `stream` as a function in the linter config as is done for `cmd`? Seems like that could work if backwards compatibility is necessary.

**Comment by cpof-tea** [comment]
> Otherwise the linter could be implemented as `function()`

I didn't know it is supported, that's why I asked.

> first calls `stylelint --version` (if that's supported), parses the version and depending on that returns a different table. But not sure if that's worth it.

Why not. At least it feels more natural, than just pretending we know if other streams used or not.

I will try to implement

**Comment by mfussenegger** [comment]
Could you first try setting the stream to `both`? If that works, it's a much simpler solution.

**Comment by cpof-tea** [comment]
@mfussenegger okay, it works.
@jmpolom could you please set `both` to `stream` option?

**Comment by albnavarro** [comment]
I think this pr can be merged as is `stream = "sterr" ` so that it is compatible with the stable version of stylelint.
Personally, to have backward compatibility I inserted:

`
 local stylelint = require("lint").linters.stylelint
`
`
stylelint.stream = "both"
`

It may be correct that the choice to use `both` is optional.

**Comment by jmpolom** [comment]
It seemed that the change by Stylelint to output errors to `stderr` was permanent. Based on that I agree with @albnavarro and this should be merged as-is. This module should support the current stable upstream linter version which outputs lint messages to `stderr`.

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-lint/pull/592

**Pull request closed without merging**
