### PR TITLE
add json parser for sqlfluff (fix #210)

### LINKED ISSUE #210: Feature Request: Support for sqlfluff
[SQLFluff](https://github.com/sqlfluff/sqlfluff) is great for SQL. Hope this can be added to your plugin.

Thank you!

### PR DESCRIPTION
**Pull request by FelipeLema**
fixes #210

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
I think the parser could be a lot easier if using `--format json`. The human output format is probably not designed for parsing and I suspect possibly not stable.

And it seems the dialect name is `postgres` not `postgresql`, at least in sqlfluff 1.2.1

**Comment by FelipeLema** [comment]
will address those... I couldn't find about json formatting ... at least, not that easily

**Comment by FelipeLema** [comment]
addressed

**Comment by mfussenegger** [comment]
Thanks

**Pull request merged**
