### PR TITLE
add markdownlint linter

### PR DESCRIPTION
**Pull request by ldelossa**
this pull adds a lint configuration for "markdownlint"

### CODE REVIEW

**Review by mfussenegger — COMMENTED** [review]
Thanks for the PR, could you maybe rebase this against latest master and use the newly improved `from_pattern` function? See https://github.com/mfussenegger/nvim-lint/pull/41

**Comment by ldelossa** [comment]
@mfussenegger done.

**Comment by mfussenegger** [comment]
Thanks :+1:

**Comment by ldelossa** [comment]
np, nice refactor btw, that function is nice and simple now.

**Comment by mfussenegger** [comment]
The credit goes to @Tastyep :)

**Pull request merged**
