### PR TITLE
feat(running linters): see the running linters for a  buffer

### PR DESCRIPTION
**Pull request by arnevm123**
Hi, 
I'd like to see which linters are currently running. This seemed like a very straightforward implementation.
I'm still fairly new to plugin development and Lua, so there might be some obvious improvements possible.

  #366

### CODE REVIEW

**Comment by arnevm123** [comment]
Hi @mfussenegger I don't know if this went under your radar or this is something you would not like added to your plugin?

**Comment by lyonelz96** [comment]
> Hi @mfussenegger I don't know if this went under your radar or this is something you would not like added to your plugin?

Would like to add that I too have been waiting for a feature like this! You're not the only one haha. Just wanted to comment to maybe raise visibility.

**Comment by ramytanios** [comment]
Would need this ! :rocket:

**Comment by chrisgrieser** [comment]
nice, thanks for this PR. For convenience, I wrapped it into a user-command, to be consistent with `:LspInfo` and `:ConformInfo`:

```lua
vim.api.nvim_create_user_command("LinterInfo", function()
	local runningLinters = table.concat(require("lint").get_running(), "\n")
	vim.notify(runningLinters, vim.log.levels.INFO, { title = "nvim-lint" })
end, {})
```

**Pull request merged**
