### PR TITLE
Add Deno lint support

### PR DESCRIPTION
**Pull request by kalmbach**
add `deno_lint` option to use the linter from deno.

### CODE REVIEW

**Comment by kalmbach** [comment]
https://github.com/mfussenegger/nvim-lint/issues/390

**Review by mfussenegger — COMMENTED** [review]
Can you rename the linter to just `deno` and add it to the readme?

**Comment by kalmbach** [comment]
> Can you rename the linter to just `deno` and add it to the readme?

Of course! Thanks for the review.

**Comment by kalmbach** [comment]
Gracias! 🙇🏻

**Pull request merged**
